language: ruby
script: 'bundle exec rake ci'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
  - jruby-20mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
notifications:
  irc:
    channels:
      - irc.freenode.org#mutant
    on_success: never
    on_failure: change
