---
UnusedParameters:
  exclude: []
UncommunicativeParameterName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
TooManyInstanceVariables:
  exclude: []
  enabled: true
  max_instance_variables: 3
TooManyMethods:
  exclude:
  - Unparser::Emitter # TODO: 13 methods, mostly helpers for deduplicate sublcasses
  enabled: true
  max_methods: 10
UncommunicativeMethodName:
  accept:
  - s
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
LongParameterList:
  max_params: 3
  exclude:
  - Unparser#self.transquote
  enabled: true
  overrides: {}
FeatureEnvy:
  exclude:
  - Unparser::Emitter::Literal::Regexp#escape # TODO Fixme!
  - Unparser::Emitter::Send#binary_receiver?
  - Unparser::Emitter#visit_terminated
  enabled: true
ClassVariable:
  exclude: []
  enabled: true
BooleanParameter:
  exclude: []
  enabled: true
IrresponsibleModule:
  exclude: []
  enabled: true
UncommunicativeModuleName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
NestedIterators:
  ignore_iterators: []
  exclude:
  - Unparser::Emitter#self.children
  - Unparser::Emitter::Literal::Regexp#dispatch
  enabled: true
  max_allowed_nesting: 1
TooManyStatements:
  max_statements: 5
  exclude:
  - Unparser#self.unparse # 6 statements
  - Unparser::Emitter::Block#dispatch # 6 statements
  - Unparser::Emitter::Def#dispatch # 6 statements
  - Unparser::Emitter::Class#dispatch # 6 statements
  - Unparser::Comments#take_eol_comments # 6 statements
  enabled: true
DuplicateMethodCall:
  allow_calls: []
  exclude: []
  enabled: false
  max_calls: 1
UtilityFunction:
  max_helper_calls: 1
  exclude: []
  enabled: true
Attribute:
  exclude: []
  enabled: false
UncommunicativeVariableName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
RepeatedConditional:
  exclude:
  - Unparser::Comments # FIXME
  - Unparser::Emitter::Send # TODO Fixme
  - Unparser::Emitter::If
  enabled: true
  max_ifs: 1
DataClump:
  exclude: []
  enabled: true
  max_copies: 1
  min_clump_size: 3
ControlParameter:
  exclude:
    - Unparser::Emitter#emit_body # false positive
  enabled: true
NilCheck:
  enabled: false
LongYieldList:
  max_params: 1
  exclude: []
  enabled: true
