inherit_from: ../.rubocop.yml

AllCops:
  Include:
    - '**/*.rake'
    - 'Gemfile'
    - 'Gemfile.triage'

# Avoid parameter lists longer than five parameters.
ParameterLists:
  Max: 3
  CountKeywordArgs: true

MethodLength:
  CountComments: false
  Max: 17

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 3

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    collect:  'map'
    inject:   'reduce'
    find:     'detect'
    find_all: 'select'

# Limit line length
LineLength:
  Max: 113  # TODO: lower to 79 once the rubocop branch in shared/Gemfile is removed

ClassLength:
  Max: 204

# Disabled because of indenting with private keyword in class bodies.
IndentationWidth:
  Enabled: false

# I like raise more
SignalException:
  Enabled: false

# False positive in unparser source
OneLineConditional:
  Enabled: false

Documentation:
  Enabled: false

# Disable documentation checking until a class needs to be documented once
Documentation:
  Enabled: false

# Do not favor modifier if/unless usage when you have a single-line body
IfUnlessModifier:
  Enabled: false

# Allow case equality operator (in limited use within the specs)
CaseEquality:
  Enabled: false

# Constants do not always have to use SCREAMING_SNAKE_CASE
ConstantName:
  Enabled: false

# Not all trivial readers/writers can be defined with attr_* methods
TrivialAccessors:
  Enabled: false

# Do not prefer do/end over {} for multiline blocks
Blocks:
  Enabled: false

# I like to have an empty line before closing the currently opened body
EmptyLinesAroundBody:
  Enabled: false

# I like my style more
AccessModifierIndentation:
  Enabled: false
